---
language: nix
env:
  global:
    - STORE=$HOME/nix-store
cache:
  directories:
    - $STORE
before_install:
  - sudo mkdir -p /etc/nix
  - echo "binary-caches = https://cache.nixos.org/ file://$STORE" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
  - mkdir -p $STORE
  - nix copy --to file://$STORE -f default.nix buildInputs
install:
  - nix-build -A buildInputs
script:
  - nix-shell --pure --command "py.test *.py"
  - nix-shell --pure --command "pylint *.py"
  - nix-shell --pure --command "flake8 *.py"
  - nix-shell --pure --command "black --check *.py"
